sudo: false
language: ruby
rvm:
- '2.4'
- '2.5'
- '2.6'
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install: gem install bundler -v 1.16.2
script: bundle exec rspec spec/
deploy:
  provider: rubygems
  gem: k8s-client
  api_key:
    secure: "f5NfPVtrGPaOCP/tnfoYRSZCRwITnQrl/YNW70gm+nk32JD1UE7qloYdNqpx4VChdFsOH/hfxygiFJkuAhvEWsx1kqOfNpVV+05r92ulp0tMyC/U1wBdnY1UEVbyZF/of25aPezx6Egkw5OFAOqUVwC6m1CqHiL91InZcE5uNtI9Kc2MHAWZqKyD7G5hau0jdFWldTS1gRrl4wJaJq0TQEWqllX6UmaW+p3pSFYKw6IekrI4LYTmCCbxRjwl2TQ8WMSTjvzEK3AIeUe7QU8bv3+56FsnCwr7dXeSK6GoDTQHZlflqYaTt6khsIXbGFCQyws4qFWu69Wf+nEJTSe7TH3qKa1WsAQy0CucVxQ5C0Lt5N5Bb2ZhqM3F2rjxeUnRBJfSRPNqyRQJUaY5GyxcEgco/rhFNJKD28sfNMqBslxGRpj2Y+hyzXt9JnRe7yEdWJcVuQLp6ObhK5DDqtcOF4aFrVd1OxZLlvl7DTHlngBuMJ7TRX50wfAkRWr4u+crrsN25j8y1KfXkTBWvlPNlReHxeT3DjPkhGuMGpy52KOtGB+5ibFvea3N2o4t9xT5pykvQ0ohwu+aj/4MroP95NKwVWZ8cbW/euOd68lwA1ZGTalPKmMWH4pPwNUmhnaCgZGexktGAVpDxFE7fZdh7gb/szfmeDDZ66eAolzrImU="
  on:
    tags: true
    rvm: '2.4'
